### ISSUE TITLE
Animation issues when importing SCML files in Godot 4.3

### ISSUE THREAD

**Issue by bnovakovic** [wojtossfm/godot_scml_importer#31]
Hello, i have encountered couple of issues when using example GreyGuy SCML file, and also with files I have purchased. Here is the info. 

**Godot version**: 4.3
**Spriter version**: Release 11 - Pro version.

Steps to reproduce: 

1. Download [GreyGuy ](https://brashmonkey.com/forum/index.php?/files/file/12-grey-guy-free-example-spriter-file-platformer-character/)example asset.
2. Unpack it, and import it in Godot.
3. You will immediately encounter error in the console that animations cannot be parsed. No animations are visible. Here is the log: https://pastebin.com/Z5sJ4u8V
![image](https://github.com/user-attachments/assets/1cb3c9f5-ca8f-45eb-9867-c5be67263c70)
4. Open `player.scml` in Spriter
5. Rename animation `idle `to `idle2`
6. Save the file, and reimport it in Godot. All animations are loaded now, and you can see them in the list.
7. Unfortunately, there is an error. Every animation has an issue. For example, walk works until the end, then player freezes, and continues. Reason for that is that there are no keyframes at the end of the animation (red rectangle bellow), and if that does not exist, animation will not work normally. Those are visible with green and red rectangle. Screenshot of the both apps are shown bellow. 
![image](https://github.com/user-attachments/assets/c03c1e36-87a0-4d07-ab67-4398c785e0ef)
8. Solution to this is to open asset in spriter, click at the very end of the animation (green rectangle), and then click the button makerd in blue (key all) to add the keyframe.
9. All animations now work properly in Godot for this asset. Other assets still have issues, but I must raise another issue about it. 
10. Unfortunately, one more minor issue remains. All animations are much slower than in Spriter.

Same asset, without any changes, worked normally with MonoGame C#. You can see it in the video I have made: https://youtu.be/AQj94xEYelc?t=1248 Timestamp 20:48.

**Comment by wojtossfm** [comment]
I would appreciate if you indeed post about issues that you have with other assets. If you have a sample project that you can share in the separate issue you raise then I am curious to see what it is and if it is something I would be able to address for you and other users.

When it comes to "GreyGuy" the README for the importer does currently state

> absolute values as found in e.g. generator version b5.95 that the GreyGuy sample comes with

While at some point I might try finding time to see what the issue is I don't think this will be anytime soon. I'm not an active user of spriter and never managed to dig into the issue in order to better understand the differences.

**Comment by bnovakovic** [comment]
I have created another issue. Assets are purchased, that seem to be tricky, but I can push it to some repo, and give you access. Let me do that.

**Comment by wojtossfm** [comment]
> I have created another issue. Assets are purchased, that seem to be tricky, but I can push it to some repo, and give you access. Let me do that.

I would be happy enough with the same asset just with some form of placeholder images instead of the actual ones. With the reference screenshot I think it should explain the issue enough.

Also I just wanted to make sure I say - Thank you for raising these. I've been trying to have the importer work to the best of my ability despite the documentation of the format that I found to be lacking.

You mentioned MonoGame - is their spriter importer a plugin that you can easily link for me or built into the engine somehow? I might try cross referencing with their implementation to better understand what might be missing.

**Comment by bnovakovic** [comment]
Hey @wojtossfm no problem mate. You did an awesome job and saved me a looooooooooooot of time, money and nerves. And I am quite sure I'm not the only one :). Thanks for this awesome importer. I have added you to my repository, you should see the invite. 

MonoGame importer is for C#, and you can see it here: https://github.com/loodakrawa/SpriterDotNet
If I'm not mistaken, Godot also supports C#, can it then be translated somehow?

Also, I linked my video above, you can see how it works.

**Comment by wojtossfm** [comment]
As I mentioned in the other issue - I believe you could use the "loop wrap interpolation" to get the result you are after. I should probably make it the default. I recall at the time when I added it I had a case that looked bad because of it but I couldn't find it currently (and it might have been a poor sample/example).

The need to re-save "Grey Guy" is at least right now expected due to no aim to support its format that has different expectations. I considered adding a better error for it (can explicitly target its version) but wanted to avoid causing versions that might work to be broken just because of a version check.

**Comment by bnovakovic** [comment]
I guess we can close this one, if you agree.
